### ISSUE TITLE
遇到一个问题，在运行时报错了，有一个文件未找到

### ISSUE THREAD

**Issue by YanYanLun** [nihgwu/react-native-sudoku#1]
2857-3357/com.liteneo.sudoku E/ReactNativeJS: Requiring unknown module "./qiniu/io.js".If you are sure the module is there, try restarting the packager or running "npm install".

**Comment by nihgwu** [comment]
Can you provide your platform info, I guess it would be something wrong with the `leancloud-storage` package, you can try to install a newer version of that

**Comment by YanYanLun** [comment]
"leancloud-storage": "^1.4.0-beta.0",
    "lodash": "^4.14.0",
    "react": "^15.3.1-rc.2",
    "react-native": "^0.34.0-rc.0",
    "react-native-device-info": "^0.9.4",
    "react-native-leancloud": "github:nihgwu/react-native-leancloud",
    "rn-splash-screen": "^2.1.0"

**Comment by leeyeh** [comment]
@yanyanlun Are you running it on Windows.

**Comment by nihgwu** [comment]
@leeyeh Have you figure out that, seems it's a issue on Windows, I haven't test it yet, but someone also report this issue to me when trying to deploy on Windows

**Comment by nihgwu** [comment]
@leeyeh seems it's using the Node version instead of Browserify version on Windoes, `qiniu` requires `fs` and other native Node modules which are incompatible with RN

**Comment by leeyeh** [comment]
I haven't test it on Windows but I believe it is a bug of react native
packager since the browser version of qiniu is bundled correctly on MacOS.

I'm planning to publish the SDK with a pre-bundled version for react native
to fix this issue.

**Comment by nihgwu** [comment]
I'm gonna to close this issue as it seems a issue with `leancloud-storage`
