### ISSUE TITLE
How to add easy medium hard level on pressing new game

### ISSUE THREAD

**Issue by abdulkabirpatel** [nihgwu/react-native-sudoku#4]
can someone tell me where is the already field cell no is in this
Beacuse I want to add levels in this

**Comment by nihgwu** [comment]
the builtin sudoku generator doesn't support custom difficulty levels, so you need to find another generator is you need different levels

**Comment by abdulkabirpatel** [comment]
but how can I increase the no. of pre-filled cells in it?
I want more cells to be filled automaticaly
